package:
  name: pysats
  version: 0.0.1

source:
  path: .
  #git_url: https://github.com/spectrumauctions/pysats.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python=3
    - cython
    - pyjnius

about:
  home: https://github.com/spectrumauctions/pysats